version: '3'

services:
  react:
    image: ${IMAGE_NAME}
    build:
      context: .
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - ${ACCESS_PORT}:3000
    stdin_open: true