version: '3'

services:
  react:
    image: ${IMAGE_NAME}
    container_name: ${IMAGE_NAME}
    build:
      context: .
    restart: always
    volumes:
      - ./react-twitter/public:/app/react-twitter/public
      - ./react-twitter/src:/app/react-twitter/src
      - ./react-twitter/.env:/app/react-twitter/.env
    ports:
      - ${ACCESS_PORT}:3000
    stdin_open: true